spring.application.name=wallet
#spring.main.web-application-type=none
#wiremock.server.stubs=file:stubs/META-INF/com.astrapay/wallet/**/mappings/**/*.json
wiremock.server.stubs = file:target/stubs/META-INF/com.astrapay/wallet/**/mappings/**/*.json
wiremock.server.port=8082


# WireMock Logging
logging.level.com.astrapay.wallet.config.WireMockAutoConfiguration=INFO
logging.level.WireMock=INFO
